apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  labels:
   app: couchdb
  namespace: proyecto
spec:
  replicas: 1
  #strategy:
  #  type: RollingUpdate
  selector:
    matchLabels:
         app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
     containers:
     - name: couchdb
       image: couchdb
       env:
        - name: COUCHDB_USER
          value: "user1"
        - name:  COUCHDB_PASSWORD
          value: "admin123"
       ports:
        - containerPort: 5984
---

apiVersion: v1
kind: Service
metadata:
 name: couchdb
 namespace: proyecto
 labels:
  app: couchdb
spec:
 type: ClusterIP 
 ports:
  - port: 5984
    targetPort: 5984
    protocol: TCP
 selector:
  app: couchdb   